### ISSUE TITLE
[Out-ConsoleGridView] Mouse doesn't work if Ubuntu (WSL) runs in Windows Terminal

### ISSUE THREAD

**Issue by alexandair** [PowerShell/GraphicalTools#51] opened 2020-03-07 18:03 UTC
Mouse doesn't work if Ubuntu (WSL) runs in Windows Terminal.
It works if Ubuntu (WSL) runs in console host.

**Comment by TylerLeonhardt** [comment] 2020-03-07 18:34
This is a dupe of https://github.com/migueldeicaza/gui.cs/issues/332 and is external to ConsoleGuiTools.

**Closed by TylerLeonhardt** 2020-03-07 18:34 UTC
Labels: Issue-gui.cs, Module-ConsoleGuiTools, Resolution-External
