### ISSUE TITLE
Module from gallery/built locally does not work in pwsh 7.1

### ISSUE THREAD

**Issue by yobyot** [PowerShell/GraphicalTools#132] opened 2020-12-23 15:34 UTC
I am unable use either Microsoft.PowerShell.GraphicalTools and Microsoft.PowerShell.ConsoleGuiTools in macOS 11.1 with PowerShell 7.1.

Here are the releases from the modules I built locally:
<img width="874" alt="modules" src="https://user-images.githubusercontent.com/14332263/103010694-b4c71b80-4506-11eb-90d1-f2dd0471458c.png">

Importing the modules from the gallery or building them locally produces the same result, shown in the animated gif below.

![pwsh](https://user-images.githubusercontent.com/14332263/103012906-4421fe00-450a-11eb-8f84-ef3689599de6.gif)

If I may make an (unsolicited) editorial comment, it seems like this module is an orphan. Does it have a future? Some of us in the PowerShell community use ogv as a "way of life." Without it, PowerShell isn't really cross-platform "enough," IMHO.

**Comment by TylerLeonhardt** [comment] 2020-12-24 04:57
@yobyot currently work on the `Microsoft.PowerShell.GraphicalTools` repo is haulted as we wait for MAUI. See this issue about that:

https://github.com/PowerShell/GraphicalTools/issues/101

Can you show us a gif of what you see when you use `Microsoft.PowerShell.ConsoleGuiTools`?

Keep in mind, the alias is `ocgv` not `ogv` (just want be clear about this)

**Comment by yobyot** [comment] 2020-12-24 20:34
I stand corrected. `Out-GridView` is dead; `Out-ConsoleGridView` still works in pwsh 7.1. But I really, *really* miss `ogv`.

![2020-12-24_15-30-07 (1)](https://user-images.githubusercontent.com/14332263/103105724-84ae7400-45fd-11eb-9a34-45a0d60e272e.gif)

**Comment by TylerLeonhardt** [comment] 2020-12-24 21:54
The reason the alias is `ocgv` instead of `ogv` is because `ogv` came back in PowerShell 7. We did the xplat `ogv` before that happened (before we thought we could ever get original, Windows-only `ogv` working)

We didn't want `ocgv` on Windows to trample the `ogv` alias so we went with `ocgv`

You could do

```pwsh
Set-Alias ogv Out-ConsoleGridView
Set-Alias Out-GridView Out-ConsoleGridView
```

In your profile so that you can have that compatibility.

I think this issue, as a whole, is a duplicate of #101 which is the pinned issue on the issues page and is the "announcement" until MAUI is in a better state.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-08-23 13:54
Indeed, @TylerLeonhardt: I believe that this should be closed, as "https://github.com/PowerShell/GraphicalTools/issues/100#issuecomment-645008475" was.

**Closed** 2023-07-19 22:44 UTC
Labels: OCGV
