### ISSUE TITLE
Out-ConsoleGridView Makes Arrow Keys Not Working

### ISSUE THREAD

**Issue by chenrylee** [PowerShell/GraphicalTools#49] opened 2020-03-07 15:51 UTC
# Steps to reproduce
1. Open the terminal (I'm using iTerm2) and run pwsh (my version is 7.0 GA)
2. Run any cmdlets and pipeline to `Out-ConsoleGridView`;<br />
```powershell
Get-ChildItem | Out-ConsoleGridView
```

3. Press `F9` and close the interface;
4. Press `up` key to quick refer the previous commands.

Now the `up` key doesn't work, I have to quit the terminal and re-open.

**Comment by TylerLeonhardt** [comment] 2020-03-07 16:32
Does it work again after you run something in the terminal like `gci`

**Comment by alexandair** [comment] 2020-03-07 17:59
I can confirm the same issue in Ubuntu (WSL).

**Comment by TylerLeonhardt** [comment] 2020-03-07 18:37
This is most certainly upstream... but I'll leave it open because I'm not sure which gui.cs issue to dupe it to and it could be fixed in one of the existing PRs.

**Comment by chenrylee** [comment] 2020-03-08 00:59
> Does it work again after you run something in the terminal like `gci`?

Nope, the only way is to restart PowerShell session, I even tried to remove and import module `PSReadLine`.

**Comment by TylerLeonhardt** [comment] 2020-03-08 04:10
This only seems to happen on Linux. macOS is not affected.

**Comment by chenrylee** [comment] 2020-03-08 05:22
> This only seems to happen on Linux. macOS is not affected.

Also on MacOS, I'm running pwsh 7.0 GA on Catalina, iTerm2.

**Comment by TylerLeonhardt** [comment] 2020-03-08 06:57
> Also on MacOS, I'm running pwsh 7.0 GA on Catalina, iTerm2.

hmm I have the same setup and can't repro...

**Comment by TylerLeonhardt** [comment] 2020-03-08 07:00
ok the up arrow seems to work after calling out to a native executable like `ls` or `cat`.

**Comment by chenrylee** [comment] 2020-03-08 08:54
> ok the up arrow seems to work after calling out to a native executable like `ls` or `cat`.

Yep, confirmed, same to me~  🌝

**Comment by TylerLeonhardt** [comment] 2020-03-10 17:12
Looks like this affects all arrow keys.

**Comment by TylerLeonhardt** [comment] 2020-03-10 18:12
Emitting `"`e[?1h"` fixes this...

**Closed** 2020-03-10 20:51 UTC
Labels: Issue-gui.cs, Module-ConsoleGuiTools, bug

**Comment by kort3x** [comment] 2020-03-13 14:48
issue persists on WSL2 on Win10 19577
