### ISSUE TITLE
Feature-Request: have a button to select all currently filtered

### ISSUE THREAD

**Issue by MrFly72** [PowerShell/GraphicalTools#149] opened 2022-04-21 19:46 UTC
It would be great to have a button to select all elements that are hit by the current filter.
EG. A list of movies is presented and the filter "Bruce" will filter all movies with Bruce Willis. 
If I press the wished button, all currently filtered will be selected.

**Comment by tig** [comment] 2022-05-27 03:04
Good suggestion!

**Comment by tig** [comment] 2022-08-04 02:04
This is a dupe of #120 which is fixed in #122.

@andschwa you can close this Issue.

**Comment by andschwa** [comment] 2022-08-04 20:36
Thanks!!

**Closed by andschwa** 2022-08-04 20:36 UTC
