### ISSUE TITLE
out-gridview doesn't work if there is a space in the property name

### ISSUE THREAD

**Issue by keith68** [PowerShell/GraphicalTools#43] opened 2020-03-03 21:17 UTC
```
PS C:\Users\KeithJohnson> [pscustomobject]@{"Field With a space" = "KJ"} | out-gridview
out-gridview : At line:1 char:10
+ $_.Field With a space
+          ~~~~
Unexpected token 'With' in expression or statement.
At line:1 char:50
+ [pscustomobject]@{"Field With a space" = "KJ"} | out-gridview
+                                                  ~~~~~~~~~~~~
+ CategoryInfo          : ParserError: (:) [Out-GridView], ParseException
+ FullyQualifiedErrorId : UnexpectedToken,OutGridView.Cmdlet.OutGridViewCmdletCommand
```

**Comment by TylerLeonhardt** [comment] 2020-03-03 21:28
This is a duplicate of #40

**Closed** 2020-03-03 21:36 UTC
Labels: duplicate
